#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running lint and format checks..."

# Lint and format backend
(cd backend && npm run lint && npm run format)
if [ $? -ne 0 ]; then
    echo "Backend linting or formatting failed."
    exit 1
fi

# Lint and format frontend
(cd frontend && npm run lint && npm run format)
if [ $? -ne 0 ]; then
    echo "Frontend linting or formatting failed."
    exit 1
fi

# Add any changed files from formatting to the commit
git add .

echo "Lint and format checks passed."
exit 0
